// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile.proto

package ru.gazprombonus.sdk.model;

public interface ApplePayPaymentDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbv1.ApplePayPaymentData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pbv1.ApplePayPaymentToken token = 1;</code>
   * @return Whether the token field is set.
   */
  boolean hasToken();
  /**
   * <code>.pbv1.ApplePayPaymentToken token = 1;</code>
   * @return The token.
   */
  ru.gazprombonus.sdk.model.ApplePayPaymentToken getToken();
  /**
   * <code>.pbv1.ApplePayPaymentToken token = 1;</code>
   */
  ru.gazprombonus.sdk.model.ApplePayPaymentTokenOrBuilder getTokenOrBuilder();
}
