// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile.proto

package ru.gazprombonus.sdk.model;

public interface BillingAddressParametersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbv1.BillingAddressParameters)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string format = 1;</code>
   * @return The format.
   */
  java.lang.String getFormat();
  /**
   * <code>string format = 1;</code>
   * @return The bytes for format.
   */
  com.google.protobuf.ByteString
      getFormatBytes();

  /**
   * <code>bool phone_number_required = 2;</code>
   * @return The phoneNumberRequired.
   */
  boolean getPhoneNumberRequired();
}
