// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile.proto

package ru.gazprombonus.sdk.model;

public interface CardInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbv1.CardInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string card_network = 1;</code>
   * @return The cardNetwork.
   */
  java.lang.String getCardNetwork();
  /**
   * <code>string card_network = 1;</code>
   * @return The bytes for cardNetwork.
   */
  com.google.protobuf.ByteString
      getCardNetworkBytes();

  /**
   * <code>string card_details = 2;</code>
   * @return The cardDetails.
   */
  java.lang.String getCardDetails();
  /**
   * <code>string card_details = 2;</code>
   * @return The bytes for cardDetails.
   */
  com.google.protobuf.ByteString
      getCardDetailsBytes();

  /**
   * <code>.pbv1.Address billing_address = 3;</code>
   * @return Whether the billingAddress field is set.
   */
  boolean hasBillingAddress();
  /**
   * <code>.pbv1.Address billing_address = 3;</code>
   * @return The billingAddress.
   */
  ru.gazprombonus.sdk.model.Address getBillingAddress();
  /**
   * <code>.pbv1.Address billing_address = 3;</code>
   */
  ru.gazprombonus.sdk.model.AddressOrBuilder getBillingAddressOrBuilder();
}
