// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile.proto

package ru.gazprombonus.sdk.model;

public interface CardParametersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbv1.CardParameters)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string allowed_auth_methods = 1;</code>
   * @return A list containing the allowedAuthMethods.
   */
  java.util.List<java.lang.String>
      getAllowedAuthMethodsList();
  /**
   * <code>repeated string allowed_auth_methods = 1;</code>
   * @return The count of allowedAuthMethods.
   */
  int getAllowedAuthMethodsCount();
  /**
   * <code>repeated string allowed_auth_methods = 1;</code>
   * @param index The index of the element to return.
   * @return The allowedAuthMethods at the given index.
   */
  java.lang.String getAllowedAuthMethods(int index);
  /**
   * <code>repeated string allowed_auth_methods = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the allowedAuthMethods at the given index.
   */
  com.google.protobuf.ByteString
      getAllowedAuthMethodsBytes(int index);

  /**
   * <code>repeated string allowed_card_networks = 2;</code>
   * @return A list containing the allowedCardNetworks.
   */
  java.util.List<java.lang.String>
      getAllowedCardNetworksList();
  /**
   * <code>repeated string allowed_card_networks = 2;</code>
   * @return The count of allowedCardNetworks.
   */
  int getAllowedCardNetworksCount();
  /**
   * <code>repeated string allowed_card_networks = 2;</code>
   * @param index The index of the element to return.
   * @return The allowedCardNetworks at the given index.
   */
  java.lang.String getAllowedCardNetworks(int index);
  /**
   * <code>repeated string allowed_card_networks = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the allowedCardNetworks at the given index.
   */
  com.google.protobuf.ByteString
      getAllowedCardNetworksBytes(int index);

  /**
   * <code>bool allow_prepaid_cards = 3;</code>
   * @return The allowPrepaidCards.
   */
  boolean getAllowPrepaidCards();

  /**
   * <code>bool allow_credit_cards = 4;</code>
   * @return The allowCreditCards.
   */
  boolean getAllowCreditCards();

  /**
   * <code>bool billing_address_required = 5;</code>
   * @return The billingAddressRequired.
   */
  boolean getBillingAddressRequired();

  /**
   * <code>.pbv1.BillingAddressParameters billing_address_parameters = 6;</code>
   * @return Whether the billingAddressParameters field is set.
   */
  boolean hasBillingAddressParameters();
  /**
   * <code>.pbv1.BillingAddressParameters billing_address_parameters = 6;</code>
   * @return The billingAddressParameters.
   */
  ru.gazprombonus.sdk.model.BillingAddressParameters getBillingAddressParameters();
  /**
   * <code>.pbv1.BillingAddressParameters billing_address_parameters = 6;</code>
   */
  ru.gazprombonus.sdk.model.BillingAddressParametersOrBuilder getBillingAddressParametersOrBuilder();

  /**
   * <code>.pbv1.CardNetworkParameters card_network_parameters = 7;</code>
   * @return Whether the cardNetworkParameters field is set.
   */
  boolean hasCardNetworkParameters();
  /**
   * <code>.pbv1.CardNetworkParameters card_network_parameters = 7;</code>
   * @return The cardNetworkParameters.
   */
  ru.gazprombonus.sdk.model.CardNetworkParameters getCardNetworkParameters();
  /**
   * <code>.pbv1.CardNetworkParameters card_network_parameters = 7;</code>
   */
  ru.gazprombonus.sdk.model.CardNetworkParametersOrBuilder getCardNetworkParametersOrBuilder();
}
