// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile.proto

package ru.gazprombonus.sdk.model;

public interface CreateKeysRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbv1.CreateKeysRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string password = 1;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 1;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
