// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile.proto

package ru.gazprombonus.sdk.model;

public interface CreateKeysResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbv1.CreateKeysResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string public_key = 1;</code>
   * @return The publicKey.
   */
  java.lang.String getPublicKey();
  /**
   * <code>string public_key = 1;</code>
   * @return The bytes for publicKey.
   */
  com.google.protobuf.ByteString
      getPublicKeyBytes();
}
