// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile.proto

package ru.gazprombonus.sdk.model;

public interface MobileEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbv1.MobileEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pbv1.MobileEventType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.pbv1.MobileEventType type = 1;</code>
   * @return The type.
   */
  ru.gazprombonus.sdk.model.MobileEventType getType();

  /**
   * <code>.pbv1.MobileError error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.pbv1.MobileError error = 2;</code>
   * @return The error.
   */
  ru.gazprombonus.sdk.model.MobileError getError();
  /**
   * <code>.pbv1.MobileError error = 2;</code>
   */
  ru.gazprombonus.sdk.model.MobileErrorOrBuilder getErrorOrBuilder();

  /**
   * <code>.pbv1.IsReadyToPayRequest is_ready_to_pay_request = 3;</code>
   * @return Whether the isReadyToPayRequest field is set.
   */
  boolean hasIsReadyToPayRequest();
  /**
   * <code>.pbv1.IsReadyToPayRequest is_ready_to_pay_request = 3;</code>
   * @return The isReadyToPayRequest.
   */
  ru.gazprombonus.sdk.model.IsReadyToPayRequest getIsReadyToPayRequest();
  /**
   * <code>.pbv1.IsReadyToPayRequest is_ready_to_pay_request = 3;</code>
   */
  ru.gazprombonus.sdk.model.IsReadyToPayRequestOrBuilder getIsReadyToPayRequestOrBuilder();

  /**
   * <code>.pbv1.PaymentDataRequest payment_data_request = 4;</code>
   * @return Whether the paymentDataRequest field is set.
   */
  boolean hasPaymentDataRequest();
  /**
   * <code>.pbv1.PaymentDataRequest payment_data_request = 4;</code>
   * @return The paymentDataRequest.
   */
  ru.gazprombonus.sdk.model.PaymentDataRequest getPaymentDataRequest();
  /**
   * <code>.pbv1.PaymentDataRequest payment_data_request = 4;</code>
   */
  ru.gazprombonus.sdk.model.PaymentDataRequestOrBuilder getPaymentDataRequestOrBuilder();

  /**
   * <code>bool is_ready_to_pay = 5;</code>
   * @return Whether the isReadyToPay field is set.
   */
  boolean hasIsReadyToPay();
  /**
   * <code>bool is_ready_to_pay = 5;</code>
   * @return The isReadyToPay.
   */
  boolean getIsReadyToPay();

  /**
   * <code>.pbv1.PaymentData payment_data = 6;</code>
   * @return Whether the paymentData field is set.
   */
  boolean hasPaymentData();
  /**
   * <code>.pbv1.PaymentData payment_data = 6;</code>
   * @return The paymentData.
   */
  ru.gazprombonus.sdk.model.PaymentData getPaymentData();
  /**
   * <code>.pbv1.PaymentData payment_data = 6;</code>
   */
  ru.gazprombonus.sdk.model.PaymentDataOrBuilder getPaymentDataOrBuilder();

  /**
   * <code>.pbv1.ApplePayPaymentDataRequest applepay_payment_data_request = 7;</code>
   * @return Whether the applepayPaymentDataRequest field is set.
   */
  boolean hasApplepayPaymentDataRequest();
  /**
   * <code>.pbv1.ApplePayPaymentDataRequest applepay_payment_data_request = 7;</code>
   * @return The applepayPaymentDataRequest.
   */
  ru.gazprombonus.sdk.model.ApplePayPaymentDataRequest getApplepayPaymentDataRequest();
  /**
   * <code>.pbv1.ApplePayPaymentDataRequest applepay_payment_data_request = 7;</code>
   */
  ru.gazprombonus.sdk.model.ApplePayPaymentDataRequestOrBuilder getApplepayPaymentDataRequestOrBuilder();

  /**
   * <code>.pbv1.ApplePayPaymentData applepay_payment_data = 8;</code>
   * @return Whether the applepayPaymentData field is set.
   */
  boolean hasApplepayPaymentData();
  /**
   * <code>.pbv1.ApplePayPaymentData applepay_payment_data = 8;</code>
   * @return The applepayPaymentData.
   */
  ru.gazprombonus.sdk.model.ApplePayPaymentData getApplepayPaymentData();
  /**
   * <code>.pbv1.ApplePayPaymentData applepay_payment_data = 8;</code>
   */
  ru.gazprombonus.sdk.model.ApplePayPaymentDataOrBuilder getApplepayPaymentDataOrBuilder();

  /**
   * <code>string open_url_request = 9;</code>
   * @return Whether the openUrlRequest field is set.
   */
  boolean hasOpenUrlRequest();
  /**
   * <code>string open_url_request = 9;</code>
   * @return The openUrlRequest.
   */
  java.lang.String getOpenUrlRequest();
  /**
   * <code>string open_url_request = 9;</code>
   * @return The bytes for openUrlRequest.
   */
  com.google.protobuf.ByteString
      getOpenUrlRequestBytes();

  /**
   * <code>string share_url_request = 10;</code>
   * @return Whether the shareUrlRequest field is set.
   */
  boolean hasShareUrlRequest();
  /**
   * <code>string share_url_request = 10;</code>
   * @return The shareUrlRequest.
   */
  java.lang.String getShareUrlRequest();
  /**
   * <code>string share_url_request = 10;</code>
   * @return The bytes for shareUrlRequest.
   */
  com.google.protobuf.ByteString
      getShareUrlRequestBytes();

  /**
   * <code>.pbv1.MobileApplicationParams application_params = 11;</code>
   * @return Whether the applicationParams field is set.
   */
  boolean hasApplicationParams();
  /**
   * <code>.pbv1.MobileApplicationParams application_params = 11;</code>
   * @return The applicationParams.
   */
  ru.gazprombonus.sdk.model.MobileApplicationParams getApplicationParams();
  /**
   * <code>.pbv1.MobileApplicationParams application_params = 11;</code>
   */
  ru.gazprombonus.sdk.model.MobileApplicationParamsOrBuilder getApplicationParamsOrBuilder();

  /**
   * <code>.pbv1.CreateKeysRequest create_keys_request = 12;</code>
   * @return Whether the createKeysRequest field is set.
   */
  boolean hasCreateKeysRequest();
  /**
   * <code>.pbv1.CreateKeysRequest create_keys_request = 12;</code>
   * @return The createKeysRequest.
   */
  ru.gazprombonus.sdk.model.CreateKeysRequest getCreateKeysRequest();
  /**
   * <code>.pbv1.CreateKeysRequest create_keys_request = 12;</code>
   */
  ru.gazprombonus.sdk.model.CreateKeysRequestOrBuilder getCreateKeysRequestOrBuilder();

  /**
   * <code>.pbv1.CreateKeysResponse create_keys_response = 13;</code>
   * @return Whether the createKeysResponse field is set.
   */
  boolean hasCreateKeysResponse();
  /**
   * <code>.pbv1.CreateKeysResponse create_keys_response = 13;</code>
   * @return The createKeysResponse.
   */
  ru.gazprombonus.sdk.model.CreateKeysResponse getCreateKeysResponse();
  /**
   * <code>.pbv1.CreateKeysResponse create_keys_response = 13;</code>
   */
  ru.gazprombonus.sdk.model.CreateKeysResponseOrBuilder getCreateKeysResponseOrBuilder();

  /**
   * <code>.pbv1.MobileApplicationParamsUpdate application_params_update = 14;</code>
   * @return Whether the applicationParamsUpdate field is set.
   */
  boolean hasApplicationParamsUpdate();
  /**
   * <code>.pbv1.MobileApplicationParamsUpdate application_params_update = 14;</code>
   * @return The applicationParamsUpdate.
   */
  ru.gazprombonus.sdk.model.MobileApplicationParamsUpdate getApplicationParamsUpdate();
  /**
   * <code>.pbv1.MobileApplicationParamsUpdate application_params_update = 14;</code>
   */
  ru.gazprombonus.sdk.model.MobileApplicationParamsUpdateOrBuilder getApplicationParamsUpdateOrBuilder();

  /**
   * <code>.pbv1.MobileAnalyticsEvent analytics_event = 15;</code>
   * @return Whether the analyticsEvent field is set.
   */
  boolean hasAnalyticsEvent();
  /**
   * <code>.pbv1.MobileAnalyticsEvent analytics_event = 15;</code>
   * @return The analyticsEvent.
   */
  ru.gazprombonus.sdk.model.MobileAnalyticsEvent getAnalyticsEvent();
  /**
   * <code>.pbv1.MobileAnalyticsEvent analytics_event = 15;</code>
   */
  ru.gazprombonus.sdk.model.MobileAnalyticsEventOrBuilder getAnalyticsEventOrBuilder();

  /**
   * <code>string clipboard_write = 16;</code>
   * @return Whether the clipboardWrite field is set.
   */
  boolean hasClipboardWrite();
  /**
   * <code>string clipboard_write = 16;</code>
   * @return The clipboardWrite.
   */
  java.lang.String getClipboardWrite();
  /**
   * <code>string clipboard_write = 16;</code>
   * @return The bytes for clipboardWrite.
   */
  com.google.protobuf.ByteString
      getClipboardWriteBytes();

  public ru.gazprombonus.sdk.model.MobileEvent.PayloadCase getPayloadCase();
}
