// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile.proto

package ru.gazprombonus.sdk.model;

public interface MobileAnalyticsEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbv1.MobileAnalyticsEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pbv1.MobileAnalyticsEventType event_type = 1;</code>
   * @return The enum numeric value on the wire for eventType.
   */
  int getEventTypeValue();
  /**
   * <code>.pbv1.MobileAnalyticsEventType event_type = 1;</code>
   * @return The eventType.
   */
  ru.gazprombonus.sdk.model.MobileAnalyticsEventType getEventType();

  /**
   * <code>string value = 2;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 2;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>string utm_medium = 3;</code>
   * @return The utmMedium.
   */
  java.lang.String getUtmMedium();
  /**
   * <code>string utm_medium = 3;</code>
   * @return The bytes for utmMedium.
   */
  com.google.protobuf.ByteString
      getUtmMediumBytes();

  /**
   * <code>string utm_source = 4;</code>
   * @return The utmSource.
   */
  java.lang.String getUtmSource();
  /**
   * <code>string utm_source = 4;</code>
   * @return The bytes for utmSource.
   */
  com.google.protobuf.ByteString
      getUtmSourceBytes();

  /**
   * <code>string utm_campaign = 5;</code>
   * @return The utmCampaign.
   */
  java.lang.String getUtmCampaign();
  /**
   * <code>string utm_campaign = 5;</code>
   * @return The bytes for utmCampaign.
   */
  com.google.protobuf.ByteString
      getUtmCampaignBytes();

  /**
   * <code>string utm_term = 6;</code>
   * @return The utmTerm.
   */
  java.lang.String getUtmTerm();
  /**
   * <code>string utm_term = 6;</code>
   * @return The bytes for utmTerm.
   */
  com.google.protobuf.ByteString
      getUtmTermBytes();

  /**
   * <code>string utm_content = 7;</code>
   * @return The utmContent.
   */
  java.lang.String getUtmContent();
  /**
   * <code>string utm_content = 7;</code>
   * @return The bytes for utmContent.
   */
  com.google.protobuf.ByteString
      getUtmContentBytes();

  /**
   * <pre>
   * [(gogoproto.stdtime) = true];
   * </pre>
   *
   * <code>.google.protobuf.Timestamp emitted_at = 8;</code>
   * @return Whether the emittedAt field is set.
   */
  boolean hasEmittedAt();
  /**
   * <pre>
   * [(gogoproto.stdtime) = true];
   * </pre>
   *
   * <code>.google.protobuf.Timestamp emitted_at = 8;</code>
   * @return The emittedAt.
   */
  com.google.protobuf.Timestamp getEmittedAt();
  /**
   * <pre>
   * [(gogoproto.stdtime) = true];
   * </pre>
   *
   * <code>.google.protobuf.Timestamp emitted_at = 8;</code>
   */
  com.google.protobuf.TimestampOrBuilder getEmittedAtOrBuilder();
}
