// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile.proto

package ru.gazprombonus.sdk.model;

public final class Mobile {
  private Mobile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_MobileEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_MobileEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_IsReadyToPayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_IsReadyToPayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_PaymentDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_PaymentDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_MerchantInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_MerchantInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_ShippingAddressParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_ShippingAddressParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_TransactionInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_TransactionInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_DisplayItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_DisplayItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_ShippingOptionParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_ShippingOptionParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_ShippingOption_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_ShippingOption_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_PaymentData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_PaymentData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_SelectionOptionData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_SelectionOptionData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_PaymentMethodData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_PaymentMethodData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_CardInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_CardInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_Address_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_PaymentMethodTokenizationData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_PaymentMethodTokenizationData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_PaymentMethodSpecification_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_PaymentMethodSpecification_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_CardParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_CardParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_TokenizationSpecification_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_TokenizationSpecification_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_TokenizationSpecification_ParametersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_TokenizationSpecification_ParametersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_BillingAddressParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_BillingAddressParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_CardNetworkParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_CardNetworkParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_MobileError_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_MobileError_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_ApplePayPaymentDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_ApplePayPaymentDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_ApplePayTotal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_ApplePayTotal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_ApplePayPaymentData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_ApplePayPaymentData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_ApplePayPaymentToken_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_ApplePayPaymentToken_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_ApplePaymentMethod_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_ApplePaymentMethod_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_MobileApplicationParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_MobileApplicationParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_MobileApplicationParamsUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_MobileApplicationParamsUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_CreateKeysRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_CreateKeysRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_CreateKeysResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_CreateKeysResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_MobileAnalyticsEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_MobileAnalyticsEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014mobile.proto\022\004pbv1\"\252\006\n\013MobileEvent\022#\n\004" +
      "type\030\001 \001(\0162\025.pbv1.MobileEventType\022\"\n\005err" +
      "or\030\002 \001(\0132\021.pbv1.MobileErrorH\000\022<\n\027is_read" +
      "y_to_pay_request\030\003 \001(\0132\031.pbv1.IsReadyToP" +
      "ayRequestH\000\0228\n\024payment_data_request\030\004 \001(" +
      "\0132\030.pbv1.PaymentDataRequestH\000\022\031\n\017is_read" +
      "y_to_pay\030\005 \001(\010H\000\022)\n\014payment_data\030\006 \001(\0132\021" +
      ".pbv1.PaymentDataH\000\022I\n\035applepay_payment_" +
      "data_request\030\007 \001(\0132 .pbv1.ApplePayPaymen" +
      "tDataRequestH\000\022:\n\025applepay_payment_data\030" +
      "\010 \001(\0132\031.pbv1.ApplePayPaymentDataH\000\022\032\n\020op" +
      "en_url_request\030\t \001(\tH\000\022\033\n\021share_url_requ" +
      "est\030\n \001(\tH\000\022;\n\022application_params\030\013 \001(\0132" +
      "\035.pbv1.MobileApplicationParamsH\000\0226\n\023crea" +
      "te_keys_request\030\014 \001(\0132\027.pbv1.CreateKeysR" +
      "equestH\000\0228\n\024create_keys_response\030\r \001(\0132\030" +
      ".pbv1.CreateKeysResponseH\000\022H\n\031applicatio" +
      "n_params_update\030\016 \001(\0132#.pbv1.MobileAppli" +
      "cationParamsUpdateH\000\0225\n\017analytics_event\030" +
      "\017 \001(\0132\032.pbv1.MobileAnalyticsEventH\000\022\031\n\017c" +
      "lipboard_write\030\020 \001(\tH\000B\t\n\007payload\"\262\001\n\023Is" +
      "ReadyToPayRequest\022\023\n\013api_version\030\001 \001(\r\022\031" +
      "\n\021api_version_minor\030\002 \001(\r\022A\n\027allowed_pay" +
      "ment_methods\030\003 \003(\0132 .pbv1.PaymentMethodS" +
      "pecification\022(\n existing_payment_method_" +
      "required\030\004 \001(\010\"\312\003\n\022PaymentDataRequest\022)\n" +
      "\rmerchant_info\030\001 \001(\0132\022.pbv1.MerchantInfo" +
      "\022\023\n\013api_version\030\002 \001(\r\022\031\n\021api_version_min" +
      "or\030\003 \001(\r\022\026\n\016email_required\030\004 \001(\010\022!\n\031ship" +
      "ping_address_required\030\005 \001(\010\022D\n\033shipping_" +
      "address_parameters\030\006 \001(\0132\037.pbv1.Shipping" +
      "AddressParameters\022A\n\027allowed_payment_met" +
      "hods\030\007 \003(\0132 .pbv1.PaymentMethodSpecifica" +
      "tion\022/\n\020transaction_info\030\010 \001(\0132\025.pbv1.Tr" +
      "ansactionInfo\022 \n\030shipping_option_require" +
      "d\030\t \001(\010\022B\n\032shipping_option_parameters\030\n " +
      "\001(\0132\036.pbv1.ShippingOptionParameters\":\n\014M" +
      "erchantInfo\022\023\n\013merchant_id\030\001 \001(\t\022\025\n\rmerc" +
      "hant_name\030\002 \001(\t\"Y\n\031ShippingAddressParame" +
      "ters\022\035\n\025allowed_country_codes\030\001 \003(\t\022\035\n\025p" +
      "hone_number_required\030\002 \001(\010\"\377\001\n\017Transacti" +
      "onInfo\022\026\n\016transaction_id\030\001 \001(\t\022\025\n\rcurren" +
      "cy_code\030\002 \001(\t\022\024\n\014country_code\030\003 \001(\t\022\023\n\013t" +
      "otal_price\030\004 \001(\t\022\031\n\021total_price_label\030\005 " +
      "\001(\t\022\032\n\022total_price_status\030\006 \001(\t\022\030\n\020trans" +
      "action_note\030\007 \001(\t\022\027\n\017checkout_option\030\010 \001" +
      "(\t\022(\n\rdisplay_items\030\t \003(\0132\021.pbv1.Display" +
      "Item\"I\n\013DisplayItem\022\r\n\005label\030\001 \001(\t\022\014\n\004ty" +
      "pe\030\002 \001(\t\022\r\n\005price\030\003 \001(\t\022\016\n\006status\030\004 \001(\t\"" +
      "n\n\030ShippingOptionParameters\022.\n\020shipping_" +
      "options\030\001 \003(\0132\024.pbv1.ShippingOption\022\"\n\032d" +
      "efault_selected_option_id\030\002 \001(\t\"@\n\016Shipp" +
      "ingOption\022\n\n\002id\030\001 \001(\t\022\r\n\005label\030\002 \001(\t\022\023\n\013" +
      "description\030\003 \001(\t\"\344\001\n\013PaymentData\022\023\n\013api" +
      "_version\030\001 \001(\r\022\031\n\021api_version_minor\030\002 \001(" +
      "\r\022\r\n\005email\030\003 \001(\t\022\'\n\020shipping_address\030\004 \001" +
      "(\0132\r.pbv1.Address\0224\n\023payment_method_data" +
      "\030\005 \001(\0132\027.pbv1.PaymentMethodData\0227\n\024shipp" +
      "ing_option_data\030\006 \001(\0132\031.pbv1.SelectionOp" +
      "tionData\"!\n\023SelectionOptionData\022\n\n\002id\030\001 " +
      "\001(\t\"\224\001\n\021PaymentMethodData\022\014\n\004type\030\001 \001(\t\022" +
      "\034\n\004info\030\002 \001(\0132\016.pbv1.CardInfo\022\023\n\013descrip" +
      "tion\030\003 \001(\t\022>\n\021tokenization_data\030\004 \001(\0132#." +
      "pbv1.PaymentMethodTokenizationData\"^\n\010Ca" +
      "rdInfo\022\024\n\014card_network\030\001 \001(\t\022\024\n\014card_det" +
      "ails\030\002 \001(\t\022&\n\017billing_address\030\003 \001(\0132\r.pb" +
      "v1.Address\"\323\001\n\007Address\022\014\n\004name\030\001 \001(\t\022\020\n\010" +
      "address1\030\002 \001(\t\022\020\n\010address2\030\003 \001(\t\022\020\n\010addr" +
      "ess3\030\004 \001(\t\022\020\n\010locality\030\005 \001(\t\022\033\n\023administ" +
      "rative_area\030\006 \001(\t\022\024\n\014country_code\030\007 \001(\t\022" +
      "\023\n\013postal_code\030\010 \001(\t\022\024\n\014sorting_code\030\t \001" +
      "(\t\022\024\n\014phone_number\030\n \001(\t\"<\n\035PaymentMetho" +
      "dTokenizationData\022\014\n\004type\030\001 \001(\t\022\r\n\005token" +
      "\030\002 \001(\t\"\231\001\n\032PaymentMethodSpecification\022\014\n" +
      "\004type\030\001 \001(\t\022(\n\nparameters\030\002 \001(\0132\024.pbv1.C" +
      "ardParameters\022C\n\032tokenization_specificat" +
      "ion\030\003 \001(\0132\037.pbv1.TokenizationSpecificati" +
      "on\"\252\002\n\016CardParameters\022\034\n\024allowed_auth_me" +
      "thods\030\001 \003(\t\022\035\n\025allowed_card_networks\030\002 \003" +
      "(\t\022\033\n\023allow_prepaid_cards\030\003 \001(\010\022\032\n\022allow" +
      "_credit_cards\030\004 \001(\010\022 \n\030billing_address_r" +
      "equired\030\005 \001(\010\022B\n\032billing_address_paramet" +
      "ers\030\006 \001(\0132\036.pbv1.BillingAddressParameter" +
      "s\022<\n\027card_network_parameters\030\007 \001(\0132\033.pbv" +
      "1.CardNetworkParameters\"\241\001\n\031Tokenization" +
      "Specification\022\014\n\004type\030\001 \001(\t\022C\n\nparameter" +
      "s\030\002 \003(\0132/.pbv1.TokenizationSpecification" +
      ".ParametersEntry\0321\n\017ParametersEntry\022\013\n\003k" +
      "ey\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"I\n\030BillingAd" +
      "dressParameters\022\016\n\006format\030\001 \001(\t\022\035\n\025phone" +
      "_number_required\030\002 \001(\010\"a\n\025CardNetworkPar" +
      "ameters\022\024\n\014card_network\030\001 \001(\t\022\024\n\014acquire" +
      "r_bin\030\002 \001(\t\022\034\n\024acquirer_merchant_id\030\003 \001(" +
      "\t\"A\n\013MobileError\022\014\n\004code\030\001 \001(\r\022\017\n\007messag" +
      "e\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\"m\n\032ApplePay" +
      "PaymentDataRequest\022\024\n\014country_code\030\001 \001(\t" +
      "\022\025\n\rcurrency_code\030\002 \001(\t\022\"\n\005total\030\003 \001(\0132\023" +
      ".pbv1.ApplePayTotal\".\n\rApplePayTotal\022\r\n\005" +
      "label\030\001 \001(\t\022\016\n\006amount\030\002 \001(\t\"@\n\023ApplePayP" +
      "aymentData\022)\n\005token\030\001 \001(\0132\032.pbv1.ApplePa" +
      "yPaymentToken\"~\n\024ApplePayPaymentToken\022\024\n" +
      "\014payment_data\030\001 \001(\t\022\036\n\026transaction_ident" +
      "ifier\030\002 \001(\t\0220\n\016payment_method\030\003 \001(\0132\030.pb" +
      "v1.ApplePaymentMethod\"I\n\022ApplePaymentMet" +
      "hod\022\024\n\014display_name\030\001 \001(\t\022\017\n\007network\030\002 \001" +
      "(\t\022\014\n\004type\030\003 \001(\t\"\367\001\n\027MobileApplicationPa" +
      "rams\022\017\n\007user_id\030\001 \001(\t\022\021\n\tdevice_id\030\002 \001(\t" +
      "\022\027\n\017confirmation_id\030\003 \001(\t\022\030\n\020password_en" +
      "abled\030\004 \001(\010\022\030\n\020biometry_enabled\030\005 \001(\010\022\032\n" +
      "\022biometry_available\030\006 \001(\010\022\021\n\tfcm_token\030\007" +
      " \001(\t\022\036\n\026my_tracker_instance_id\030\010 \001(\t\022\034\n\024" +
      "appmetrica_device_id\030\t \001(\t\"}\n\035MobileAppl" +
      "icationParamsUpdate\022\017\n\007user_id\030\001 \001(\t\022\027\n\017" +
      "confirmation_id\030\002 \001(\t\022\030\n\020password_enable" +
      "d\030\003 \001(\010\022\030\n\020biometry_enabled\030\004 \001(\010\"%\n\021Cre" +
      "ateKeysRequest\022\020\n\010password\030\001 \001(\t\"(\n\022Crea" +
      "teKeysResponse\022\022\n\npublic_key\030\001 \001(\t\"\276\001\n\024M" +
      "obileAnalyticsEvent\0222\n\nevent_type\030\001 \001(\0162" +
      "\036.pbv1.MobileAnalyticsEventType\022\r\n\005value" +
      "\030\002 \001(\t\022\022\n\nutm_medium\030\003 \001(\t\022\022\n\nutm_source" +
      "\030\004 \001(\t\022\024\n\014utm_campaign\030\005 \001(\t\022\020\n\010utm_term" +
      "\030\006 \001(\t\022\023\n\013utm_content\030\007 \001(\t*\271\007\n\017MobileEv" +
      "entType\022\034\n\030MOBILE_EVENT_UNSPECIFIED\020\000\0222\n" +
      ".MOBILE_EVENT_GOOGLEPAY_IS_READY_TO_PAY_" +
      "REQUEST\020\001\0223\n/MOBILE_EVENT_GOOGLEPAY_IS_R" +
      "EADY_TO_PAY_RESPONSE\020\002\022/\n+MOBILE_EVENT_G" +
      "OOGLEPAY_PAYMENT_DATA_REQUEST\020\003\0220\n,MOBIL" +
      "E_EVENT_GOOGLEPAY_PAYMENT_DATA_RESPONSE\020" +
      "\004\022-\n)MOBILE_EVENT_GOOGLEPAY_PAYMENT_DATA" +
      "_ERROR\020\005\0221\n-MOBILE_EVENT_APPLEPAY_IS_REA" +
      "DY_TO_PAY_REQUEST\020\006\0222\n.MOBILE_EVENT_APPL" +
      "EPAY_IS_READY_TO_PAY_RESPONSE\020\007\022.\n*MOBIL" +
      "E_EVENT_APPLEPAY_PAYMENT_DATA_REQUEST\020\010\022" +
      "/\n+MOBILE_EVENT_APPLEPAY_PAYMENT_DATA_RE" +
      "SPONSE\020\t\022,\n(MOBILE_EVENT_APPLEPAY_PAYMEN" +
      "T_DATA_ERROR\020\n\022!\n\035MOBILE_EVENT_OPEN_URL_" +
      "REQUEST\020\013\022\025\n\021MOBILE_EVENT_BACK\020\014\022\"\n\036MOBI" +
      "LE_EVENT_SHARE_URL_REQUEST\020\r\022#\n\037MOBILE_E" +
      "VENT_GET_PARAMS_REQUEST\020\016\022$\n MOBILE_EVEN" +
      "T_GET_PARAMS_RESPONSE\020\017\022#\n\037MOBILE_EVENT_" +
      "SET_PARAMS_REQUEST\020\020\022$\n MOBILE_EVENT_CRE" +
      "ATE_KEYS_REQUEST\020\021\022%\n!MOBILE_EVENT_CREAT" +
      "E_KEYS_RESPONSE\020\022\022\037\n\033MOBILE_EVENT_PARAMS" +
      "_UPDATED\020\023\022 \n\034MOBILE_EVENT_ANALYTICS_EVE" +
      "NT\020\024\022 \n\034MOBILE_EVENT_CLIPBOARD_WRITE\020\025\022\027" +
      "\n\023MOBILE_EVENT_REVIEW\020\026*\356\001\n\030MobileAnalyt" +
      "icsEventType\022+\n\'MOBILE_ANALYTICS_EVENT_T" +
      "YPE_UNSPECIFIED\020\000\022<\n8MOBILE_ANALYTICS_EV" +
      "ENT_TYPE_ANDROID_APP_INSTALL_REFERRER\020\001\022" +
      "3\n/MOBILE_ANALYTICS_EVENT_TYPE_ANDROID_I" +
      "AU_INSTALL\020\002\0222\n.MOBILE_ANALYTICS_EVENT_T" +
      "YPE_ANDROID_IAU_CANCEL\020\003B\035\n\031ru.gazprombo" +
      "nus.sdk.modelP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pbv1_MobileEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pbv1_MobileEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_MobileEvent_descriptor,
        new java.lang.String[] { "Type", "Error", "IsReadyToPayRequest", "PaymentDataRequest", "IsReadyToPay", "PaymentData", "ApplepayPaymentDataRequest", "ApplepayPaymentData", "OpenUrlRequest", "ShareUrlRequest", "ApplicationParams", "CreateKeysRequest", "CreateKeysResponse", "ApplicationParamsUpdate", "AnalyticsEvent", "ClipboardWrite", "Payload", });
    internal_static_pbv1_IsReadyToPayRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pbv1_IsReadyToPayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_IsReadyToPayRequest_descriptor,
        new java.lang.String[] { "ApiVersion", "ApiVersionMinor", "AllowedPaymentMethods", "ExistingPaymentMethodRequired", });
    internal_static_pbv1_PaymentDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pbv1_PaymentDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_PaymentDataRequest_descriptor,
        new java.lang.String[] { "MerchantInfo", "ApiVersion", "ApiVersionMinor", "EmailRequired", "ShippingAddressRequired", "ShippingAddressParameters", "AllowedPaymentMethods", "TransactionInfo", "ShippingOptionRequired", "ShippingOptionParameters", });
    internal_static_pbv1_MerchantInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_pbv1_MerchantInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_MerchantInfo_descriptor,
        new java.lang.String[] { "MerchantId", "MerchantName", });
    internal_static_pbv1_ShippingAddressParameters_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_pbv1_ShippingAddressParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_ShippingAddressParameters_descriptor,
        new java.lang.String[] { "AllowedCountryCodes", "PhoneNumberRequired", });
    internal_static_pbv1_TransactionInfo_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_pbv1_TransactionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_TransactionInfo_descriptor,
        new java.lang.String[] { "TransactionId", "CurrencyCode", "CountryCode", "TotalPrice", "TotalPriceLabel", "TotalPriceStatus", "TransactionNote", "CheckoutOption", "DisplayItems", });
    internal_static_pbv1_DisplayItem_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_pbv1_DisplayItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_DisplayItem_descriptor,
        new java.lang.String[] { "Label", "Type", "Price", "Status", });
    internal_static_pbv1_ShippingOptionParameters_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_pbv1_ShippingOptionParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_ShippingOptionParameters_descriptor,
        new java.lang.String[] { "ShippingOptions", "DefaultSelectedOptionId", });
    internal_static_pbv1_ShippingOption_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_pbv1_ShippingOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_ShippingOption_descriptor,
        new java.lang.String[] { "Id", "Label", "Description", });
    internal_static_pbv1_PaymentData_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_pbv1_PaymentData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_PaymentData_descriptor,
        new java.lang.String[] { "ApiVersion", "ApiVersionMinor", "Email", "ShippingAddress", "PaymentMethodData", "ShippingOptionData", });
    internal_static_pbv1_SelectionOptionData_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_pbv1_SelectionOptionData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_SelectionOptionData_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_pbv1_PaymentMethodData_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_pbv1_PaymentMethodData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_PaymentMethodData_descriptor,
        new java.lang.String[] { "Type", "Info", "Description", "TokenizationData", });
    internal_static_pbv1_CardInfo_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_pbv1_CardInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_CardInfo_descriptor,
        new java.lang.String[] { "CardNetwork", "CardDetails", "BillingAddress", });
    internal_static_pbv1_Address_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_pbv1_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_Address_descriptor,
        new java.lang.String[] { "Name", "Address1", "Address2", "Address3", "Locality", "AdministrativeArea", "CountryCode", "PostalCode", "SortingCode", "PhoneNumber", });
    internal_static_pbv1_PaymentMethodTokenizationData_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_pbv1_PaymentMethodTokenizationData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_PaymentMethodTokenizationData_descriptor,
        new java.lang.String[] { "Type", "Token", });
    internal_static_pbv1_PaymentMethodSpecification_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_pbv1_PaymentMethodSpecification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_PaymentMethodSpecification_descriptor,
        new java.lang.String[] { "Type", "Parameters", "TokenizationSpecification", });
    internal_static_pbv1_CardParameters_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_pbv1_CardParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_CardParameters_descriptor,
        new java.lang.String[] { "AllowedAuthMethods", "AllowedCardNetworks", "AllowPrepaidCards", "AllowCreditCards", "BillingAddressRequired", "BillingAddressParameters", "CardNetworkParameters", });
    internal_static_pbv1_TokenizationSpecification_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_pbv1_TokenizationSpecification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_TokenizationSpecification_descriptor,
        new java.lang.String[] { "Type", "Parameters", });
    internal_static_pbv1_TokenizationSpecification_ParametersEntry_descriptor =
      internal_static_pbv1_TokenizationSpecification_descriptor.getNestedTypes().get(0);
    internal_static_pbv1_TokenizationSpecification_ParametersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_TokenizationSpecification_ParametersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_pbv1_BillingAddressParameters_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_pbv1_BillingAddressParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_BillingAddressParameters_descriptor,
        new java.lang.String[] { "Format", "PhoneNumberRequired", });
    internal_static_pbv1_CardNetworkParameters_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_pbv1_CardNetworkParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_CardNetworkParameters_descriptor,
        new java.lang.String[] { "CardNetwork", "AcquirerBin", "AcquirerMerchantId", });
    internal_static_pbv1_MobileError_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_pbv1_MobileError_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_MobileError_descriptor,
        new java.lang.String[] { "Code", "Message", "Description", });
    internal_static_pbv1_ApplePayPaymentDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_pbv1_ApplePayPaymentDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_ApplePayPaymentDataRequest_descriptor,
        new java.lang.String[] { "CountryCode", "CurrencyCode", "Total", });
    internal_static_pbv1_ApplePayTotal_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_pbv1_ApplePayTotal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_ApplePayTotal_descriptor,
        new java.lang.String[] { "Label", "Amount", });
    internal_static_pbv1_ApplePayPaymentData_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_pbv1_ApplePayPaymentData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_ApplePayPaymentData_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_pbv1_ApplePayPaymentToken_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_pbv1_ApplePayPaymentToken_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_ApplePayPaymentToken_descriptor,
        new java.lang.String[] { "PaymentData", "TransactionIdentifier", "PaymentMethod", });
    internal_static_pbv1_ApplePaymentMethod_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_pbv1_ApplePaymentMethod_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_ApplePaymentMethod_descriptor,
        new java.lang.String[] { "DisplayName", "Network", "Type", });
    internal_static_pbv1_MobileApplicationParams_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_pbv1_MobileApplicationParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_MobileApplicationParams_descriptor,
        new java.lang.String[] { "UserId", "DeviceId", "ConfirmationId", "PasswordEnabled", "BiometryEnabled", "BiometryAvailable", "FcmToken", "MyTrackerInstanceId", "AppmetricaDeviceId", });
    internal_static_pbv1_MobileApplicationParamsUpdate_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_pbv1_MobileApplicationParamsUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_MobileApplicationParamsUpdate_descriptor,
        new java.lang.String[] { "UserId", "ConfirmationId", "PasswordEnabled", "BiometryEnabled", });
    internal_static_pbv1_CreateKeysRequest_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_pbv1_CreateKeysRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_CreateKeysRequest_descriptor,
        new java.lang.String[] { "Password", });
    internal_static_pbv1_CreateKeysResponse_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_pbv1_CreateKeysResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_CreateKeysResponse_descriptor,
        new java.lang.String[] { "PublicKey", });
    internal_static_pbv1_MobileAnalyticsEvent_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_pbv1_MobileAnalyticsEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_MobileAnalyticsEvent_descriptor,
        new java.lang.String[] { "EventType", "Value", "UtmMedium", "UtmSource", "UtmCampaign", "UtmTerm", "UtmContent", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
