// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile.proto

package ru.gazprombonus.sdk.model;

public interface MobileApplicationParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbv1.MobileApplicationParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string device_id = 2;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 2;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>string confirmation_id = 3;</code>
   * @return The confirmationId.
   */
  java.lang.String getConfirmationId();
  /**
   * <code>string confirmation_id = 3;</code>
   * @return The bytes for confirmationId.
   */
  com.google.protobuf.ByteString
      getConfirmationIdBytes();

  /**
   * <code>bool password_enabled = 4;</code>
   * @return The passwordEnabled.
   */
  boolean getPasswordEnabled();

  /**
   * <code>bool biometry_enabled = 5;</code>
   * @return The biometryEnabled.
   */
  boolean getBiometryEnabled();

  /**
   * <code>bool biometry_available = 6;</code>
   * @return The biometryAvailable.
   */
  boolean getBiometryAvailable();

  /**
   * <code>string fcm_token = 7;</code>
   * @return The fcmToken.
   */
  java.lang.String getFcmToken();
  /**
   * <code>string fcm_token = 7;</code>
   * @return The bytes for fcmToken.
   */
  com.google.protobuf.ByteString
      getFcmTokenBytes();

  /**
   * <code>string my_tracker_instance_id = 8;</code>
   * @return The myTrackerInstanceId.
   */
  java.lang.String getMyTrackerInstanceId();
  /**
   * <code>string my_tracker_instance_id = 8;</code>
   * @return The bytes for myTrackerInstanceId.
   */
  com.google.protobuf.ByteString
      getMyTrackerInstanceIdBytes();

  /**
   * <code>string appmetrica_device_id = 9;</code>
   * @return The appmetricaDeviceId.
   */
  java.lang.String getAppmetricaDeviceId();
  /**
   * <code>string appmetrica_device_id = 9;</code>
   * @return The bytes for appmetricaDeviceId.
   */
  com.google.protobuf.ByteString
      getAppmetricaDeviceIdBytes();
}
