// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile.proto

package ru.gazprombonus.sdk.model;

public interface MobileApplicationParamsUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbv1.MobileApplicationParamsUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string confirmation_id = 2;</code>
   * @return The confirmationId.
   */
  java.lang.String getConfirmationId();
  /**
   * <code>string confirmation_id = 2;</code>
   * @return The bytes for confirmationId.
   */
  com.google.protobuf.ByteString
      getConfirmationIdBytes();

  /**
   * <code>bool password_enabled = 3;</code>
   * @return The passwordEnabled.
   */
  boolean getPasswordEnabled();

  /**
   * <code>bool biometry_enabled = 4;</code>
   * @return The biometryEnabled.
   */
  boolean getBiometryEnabled();
}
