// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile.proto

package ru.gazprombonus.sdk.model;

public final class Mobile {
  private Mobile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_MobileEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_MobileEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_IsReadyToPayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_IsReadyToPayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_PaymentDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_PaymentDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_MerchantInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_MerchantInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_ShippingAddressParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_ShippingAddressParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_TransactionInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_TransactionInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_DisplayItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_DisplayItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_ShippingOptionParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_ShippingOptionParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_ShippingOption_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_ShippingOption_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_PaymentData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_PaymentData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_SelectionOptionData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_SelectionOptionData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_PaymentMethodData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_PaymentMethodData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_CardInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_CardInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_Address_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_PaymentMethodTokenizationData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_PaymentMethodTokenizationData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_PaymentMethodSpecification_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_PaymentMethodSpecification_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_CardParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_CardParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_TokenizationSpecification_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_TokenizationSpecification_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_TokenizationSpecification_ParametersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_TokenizationSpecification_ParametersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_BillingAddressParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_BillingAddressParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_CardNetworkParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_CardNetworkParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_MobileError_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_MobileError_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_ApplePayPaymentDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_ApplePayPaymentDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_ApplePayTotal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_ApplePayTotal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_ApplePayPaymentData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_ApplePayPaymentData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_ApplePayPaymentToken_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_ApplePayPaymentToken_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_ApplePaymentMethod_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_ApplePaymentMethod_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_MobileApplicationParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_MobileApplicationParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_MobileApplicationParamsUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_MobileApplicationParamsUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_CreateKeysRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_CreateKeysRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_CreateKeysResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_CreateKeysResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pbv1_MobileAnalyticsEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pbv1_MobileAnalyticsEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014mobile.proto\022\004pbv1\032\037google/protobuf/ti" +
      "mestamp.proto\"\252\006\n\013MobileEvent\022#\n\004type\030\001 " +
      "\001(\0162\025.pbv1.MobileEventType\022\"\n\005error\030\002 \001(" +
      "\0132\021.pbv1.MobileErrorH\000\022<\n\027is_ready_to_pa" +
      "y_request\030\003 \001(\0132\031.pbv1.IsReadyToPayReque" +
      "stH\000\0228\n\024payment_data_request\030\004 \001(\0132\030.pbv" +
      "1.PaymentDataRequestH\000\022\031\n\017is_ready_to_pa" +
      "y\030\005 \001(\010H\000\022)\n\014payment_data\030\006 \001(\0132\021.pbv1.P" +
      "aymentDataH\000\022I\n\035applepay_payment_data_re" +
      "quest\030\007 \001(\0132 .pbv1.ApplePayPaymentDataRe" +
      "questH\000\022:\n\025applepay_payment_data\030\010 \001(\0132\031" +
      ".pbv1.ApplePayPaymentDataH\000\022\032\n\020open_url_" +
      "request\030\t \001(\tH\000\022\033\n\021share_url_request\030\n \001" +
      "(\tH\000\022;\n\022application_params\030\013 \001(\0132\035.pbv1." +
      "MobileApplicationParamsH\000\0226\n\023create_keys" +
      "_request\030\014 \001(\0132\027.pbv1.CreateKeysRequestH" +
      "\000\0228\n\024create_keys_response\030\r \001(\0132\030.pbv1.C" +
      "reateKeysResponseH\000\022H\n\031application_param" +
      "s_update\030\016 \001(\0132#.pbv1.MobileApplicationP" +
      "aramsUpdateH\000\0225\n\017analytics_event\030\017 \001(\0132\032" +
      ".pbv1.MobileAnalyticsEventH\000\022\031\n\017clipboar" +
      "d_write\030\020 \001(\tH\000B\t\n\007payload\"\262\001\n\023IsReadyTo" +
      "PayRequest\022\023\n\013api_version\030\001 \001(\r\022\031\n\021api_v" +
      "ersion_minor\030\002 \001(\r\022A\n\027allowed_payment_me" +
      "thods\030\003 \003(\0132 .pbv1.PaymentMethodSpecific" +
      "ation\022(\n existing_payment_method_require" +
      "d\030\004 \001(\010\"\312\003\n\022PaymentDataRequest\022)\n\rmercha" +
      "nt_info\030\001 \001(\0132\022.pbv1.MerchantInfo\022\023\n\013api" +
      "_version\030\002 \001(\r\022\031\n\021api_version_minor\030\003 \001(" +
      "\r\022\026\n\016email_required\030\004 \001(\010\022!\n\031shipping_ad" +
      "dress_required\030\005 \001(\010\022D\n\033shipping_address" +
      "_parameters\030\006 \001(\0132\037.pbv1.ShippingAddress" +
      "Parameters\022A\n\027allowed_payment_methods\030\007 " +
      "\003(\0132 .pbv1.PaymentMethodSpecification\022/\n" +
      "\020transaction_info\030\010 \001(\0132\025.pbv1.Transacti" +
      "onInfo\022 \n\030shipping_option_required\030\t \001(\010" +
      "\022B\n\032shipping_option_parameters\030\n \001(\0132\036.p" +
      "bv1.ShippingOptionParameters\":\n\014Merchant" +
      "Info\022\023\n\013merchant_id\030\001 \001(\t\022\025\n\rmerchant_na" +
      "me\030\002 \001(\t\"Y\n\031ShippingAddressParameters\022\035\n" +
      "\025allowed_country_codes\030\001 \003(\t\022\035\n\025phone_nu" +
      "mber_required\030\002 \001(\010\"\377\001\n\017TransactionInfo\022" +
      "\026\n\016transaction_id\030\001 \001(\t\022\025\n\rcurrency_code" +
      "\030\002 \001(\t\022\024\n\014country_code\030\003 \001(\t\022\023\n\013total_pr" +
      "ice\030\004 \001(\t\022\031\n\021total_price_label\030\005 \001(\t\022\032\n\022" +
      "total_price_status\030\006 \001(\t\022\030\n\020transaction_" +
      "note\030\007 \001(\t\022\027\n\017checkout_option\030\010 \001(\t\022(\n\rd" +
      "isplay_items\030\t \003(\0132\021.pbv1.DisplayItem\"I\n" +
      "\013DisplayItem\022\r\n\005label\030\001 \001(\t\022\014\n\004type\030\002 \001(" +
      "\t\022\r\n\005price\030\003 \001(\t\022\016\n\006status\030\004 \001(\t\"n\n\030Ship" +
      "pingOptionParameters\022.\n\020shipping_options" +
      "\030\001 \003(\0132\024.pbv1.ShippingOption\022\"\n\032default_" +
      "selected_option_id\030\002 \001(\t\"@\n\016ShippingOpti" +
      "on\022\n\n\002id\030\001 \001(\t\022\r\n\005label\030\002 \001(\t\022\023\n\013descrip" +
      "tion\030\003 \001(\t\"\344\001\n\013PaymentData\022\023\n\013api_versio" +
      "n\030\001 \001(\r\022\031\n\021api_version_minor\030\002 \001(\r\022\r\n\005em" +
      "ail\030\003 \001(\t\022\'\n\020shipping_address\030\004 \001(\0132\r.pb" +
      "v1.Address\0224\n\023payment_method_data\030\005 \001(\0132" +
      "\027.pbv1.PaymentMethodData\0227\n\024shipping_opt" +
      "ion_data\030\006 \001(\0132\031.pbv1.SelectionOptionDat" +
      "a\"!\n\023SelectionOptionData\022\n\n\002id\030\001 \001(\t\"\224\001\n" +
      "\021PaymentMethodData\022\014\n\004type\030\001 \001(\t\022\034\n\004info" +
      "\030\002 \001(\0132\016.pbv1.CardInfo\022\023\n\013description\030\003 " +
      "\001(\t\022>\n\021tokenization_data\030\004 \001(\0132#.pbv1.Pa" +
      "ymentMethodTokenizationData\"^\n\010CardInfo\022" +
      "\024\n\014card_network\030\001 \001(\t\022\024\n\014card_details\030\002 " +
      "\001(\t\022&\n\017billing_address\030\003 \001(\0132\r.pbv1.Addr" +
      "ess\"\323\001\n\007Address\022\014\n\004name\030\001 \001(\t\022\020\n\010address" +
      "1\030\002 \001(\t\022\020\n\010address2\030\003 \001(\t\022\020\n\010address3\030\004 " +
      "\001(\t\022\020\n\010locality\030\005 \001(\t\022\033\n\023administrative_" +
      "area\030\006 \001(\t\022\024\n\014country_code\030\007 \001(\t\022\023\n\013post" +
      "al_code\030\010 \001(\t\022\024\n\014sorting_code\030\t \001(\t\022\024\n\014p" +
      "hone_number\030\n \001(\t\"<\n\035PaymentMethodTokeni" +
      "zationData\022\014\n\004type\030\001 \001(\t\022\r\n\005token\030\002 \001(\t\"" +
      "\231\001\n\032PaymentMethodSpecification\022\014\n\004type\030\001" +
      " \001(\t\022(\n\nparameters\030\002 \001(\0132\024.pbv1.CardPara" +
      "meters\022C\n\032tokenization_specification\030\003 \001" +
      "(\0132\037.pbv1.TokenizationSpecification\"\252\002\n\016" +
      "CardParameters\022\034\n\024allowed_auth_methods\030\001" +
      " \003(\t\022\035\n\025allowed_card_networks\030\002 \003(\t\022\033\n\023a" +
      "llow_prepaid_cards\030\003 \001(\010\022\032\n\022allow_credit" +
      "_cards\030\004 \001(\010\022 \n\030billing_address_required" +
      "\030\005 \001(\010\022B\n\032billing_address_parameters\030\006 \001" +
      "(\0132\036.pbv1.BillingAddressParameters\022<\n\027ca" +
      "rd_network_parameters\030\007 \001(\0132\033.pbv1.CardN" +
      "etworkParameters\"\241\001\n\031TokenizationSpecifi" +
      "cation\022\014\n\004type\030\001 \001(\t\022C\n\nparameters\030\002 \003(\013" +
      "2/.pbv1.TokenizationSpecification.Parame" +
      "tersEntry\0321\n\017ParametersEntry\022\013\n\003key\030\001 \001(" +
      "\t\022\r\n\005value\030\002 \001(\t:\0028\001\"I\n\030BillingAddressPa" +
      "rameters\022\016\n\006format\030\001 \001(\t\022\035\n\025phone_number" +
      "_required\030\002 \001(\010\"a\n\025CardNetworkParameters" +
      "\022\024\n\014card_network\030\001 \001(\t\022\024\n\014acquirer_bin\030\002" +
      " \001(\t\022\034\n\024acquirer_merchant_id\030\003 \001(\t\"A\n\013Mo" +
      "bileError\022\014\n\004code\030\001 \001(\r\022\017\n\007message\030\002 \001(\t" +
      "\022\023\n\013description\030\003 \001(\t\"m\n\032ApplePayPayment" +
      "DataRequest\022\024\n\014country_code\030\001 \001(\t\022\025\n\rcur" +
      "rency_code\030\002 \001(\t\022\"\n\005total\030\003 \001(\0132\023.pbv1.A" +
      "pplePayTotal\".\n\rApplePayTotal\022\r\n\005label\030\001" +
      " \001(\t\022\016\n\006amount\030\002 \001(\t\"@\n\023ApplePayPaymentD" +
      "ata\022)\n\005token\030\001 \001(\0132\032.pbv1.ApplePayPaymen" +
      "tToken\"~\n\024ApplePayPaymentToken\022\024\n\014paymen" +
      "t_data\030\001 \001(\t\022\036\n\026transaction_identifier\030\002" +
      " \001(\t\0220\n\016payment_method\030\003 \001(\0132\030.pbv1.Appl" +
      "ePaymentMethod\"I\n\022ApplePaymentMethod\022\024\n\014" +
      "display_name\030\001 \001(\t\022\017\n\007network\030\002 \001(\t\022\014\n\004t" +
      "ype\030\003 \001(\t\"\367\001\n\027MobileApplicationParams\022\017\n" +
      "\007user_id\030\001 \001(\t\022\021\n\tdevice_id\030\002 \001(\t\022\027\n\017con" +
      "firmation_id\030\003 \001(\t\022\030\n\020password_enabled\030\004" +
      " \001(\010\022\030\n\020biometry_enabled\030\005 \001(\010\022\032\n\022biomet" +
      "ry_available\030\006 \001(\010\022\021\n\tfcm_token\030\007 \001(\t\022\036\n" +
      "\026my_tracker_instance_id\030\010 \001(\t\022\034\n\024appmetr" +
      "ica_device_id\030\t \001(\t\"}\n\035MobileApplication" +
      "ParamsUpdate\022\017\n\007user_id\030\001 \001(\t\022\027\n\017confirm" +
      "ation_id\030\002 \001(\t\022\030\n\020password_enabled\030\003 \001(\010" +
      "\022\030\n\020biometry_enabled\030\004 \001(\010\"%\n\021CreateKeys" +
      "Request\022\020\n\010password\030\001 \001(\t\"(\n\022CreateKeysR" +
      "esponse\022\022\n\npublic_key\030\001 \001(\t\"\356\001\n\024MobileAn" +
      "alyticsEvent\0222\n\nevent_type\030\001 \001(\0162\036.pbv1." +
      "MobileAnalyticsEventType\022\r\n\005value\030\002 \001(\t\022" +
      "\022\n\nutm_medium\030\003 \001(\t\022\022\n\nutm_source\030\004 \001(\t\022" +
      "\024\n\014utm_campaign\030\005 \001(\t\022\020\n\010utm_term\030\006 \001(\t\022" +
      "\023\n\013utm_content\030\007 \001(\t\022.\n\nemitted_at\030\010 \001(\013" +
      "2\032.google.protobuf.Timestamp*\271\007\n\017MobileE" +
      "ventType\022\034\n\030MOBILE_EVENT_UNSPECIFIED\020\000\0222" +
      "\n.MOBILE_EVENT_GOOGLEPAY_IS_READY_TO_PAY" +
      "_REQUEST\020\001\0223\n/MOBILE_EVENT_GOOGLEPAY_IS_" +
      "READY_TO_PAY_RESPONSE\020\002\022/\n+MOBILE_EVENT_" +
      "GOOGLEPAY_PAYMENT_DATA_REQUEST\020\003\0220\n,MOBI" +
      "LE_EVENT_GOOGLEPAY_PAYMENT_DATA_RESPONSE" +
      "\020\004\022-\n)MOBILE_EVENT_GOOGLEPAY_PAYMENT_DAT" +
      "A_ERROR\020\005\0221\n-MOBILE_EVENT_APPLEPAY_IS_RE" +
      "ADY_TO_PAY_REQUEST\020\006\0222\n.MOBILE_EVENT_APP" +
      "LEPAY_IS_READY_TO_PAY_RESPONSE\020\007\022.\n*MOBI" +
      "LE_EVENT_APPLEPAY_PAYMENT_DATA_REQUEST\020\010" +
      "\022/\n+MOBILE_EVENT_APPLEPAY_PAYMENT_DATA_R" +
      "ESPONSE\020\t\022,\n(MOBILE_EVENT_APPLEPAY_PAYME" +
      "NT_DATA_ERROR\020\n\022!\n\035MOBILE_EVENT_OPEN_URL" +
      "_REQUEST\020\013\022\025\n\021MOBILE_EVENT_BACK\020\014\022\"\n\036MOB" +
      "ILE_EVENT_SHARE_URL_REQUEST\020\r\022#\n\037MOBILE_" +
      "EVENT_GET_PARAMS_REQUEST\020\016\022$\n MOBILE_EVE" +
      "NT_GET_PARAMS_RESPONSE\020\017\022#\n\037MOBILE_EVENT" +
      "_SET_PARAMS_REQUEST\020\020\022$\n MOBILE_EVENT_CR" +
      "EATE_KEYS_REQUEST\020\021\022%\n!MOBILE_EVENT_CREA" +
      "TE_KEYS_RESPONSE\020\022\022\037\n\033MOBILE_EVENT_PARAM" +
      "S_UPDATED\020\023\022 \n\034MOBILE_EVENT_ANALYTICS_EV" +
      "ENT\020\024\022 \n\034MOBILE_EVENT_CLIPBOARD_WRITE\020\025\022" +
      "\027\n\023MOBILE_EVENT_REVIEW\020\026*\277\003\n\030MobileAnaly" +
      "ticsEventType\022+\n\'MOBILE_ANALYTICS_EVENT_" +
      "TYPE_UNSPECIFIED\020\000\022<\n8MOBILE_ANALYTICS_E" +
      "VENT_TYPE_ANDROID_APP_INSTALL_REFERRER\020\001" +
      "\0223\n/MOBILE_ANALYTICS_EVENT_TYPE_ANDROID_" +
      "IAU_INSTALL\020\002\0222\n.MOBILE_ANALYTICS_EVENT_" +
      "TYPE_ANDROID_IAU_CANCEL\020\003\0222\n.MOBILE_ANAL" +
      "YTICS_EVENT_TYPE_LOGIN_APP_PASSWORD\020\004\0222\n" +
      ".MOBILE_ANALYTICS_EVENT_TYPE_LOGIN_APP_B" +
      "IOMETRY\020\005\0222\n.MOBILE_ANALYTICS_EVENT_TYPE" +
      "_APP_BIOMETRY_RESET\020\006\0223\n/MOBILE_ANALYTIC" +
      "S_EVENT_TYPE_ERROR_AUTH_BIOMETRY\020\007B\035\n\031ru" +
      ".gazprombonus.sdk.modelP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_pbv1_MobileEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pbv1_MobileEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_MobileEvent_descriptor,
        new java.lang.String[] { "Type", "Error", "IsReadyToPayRequest", "PaymentDataRequest", "IsReadyToPay", "PaymentData", "ApplepayPaymentDataRequest", "ApplepayPaymentData", "OpenUrlRequest", "ShareUrlRequest", "ApplicationParams", "CreateKeysRequest", "CreateKeysResponse", "ApplicationParamsUpdate", "AnalyticsEvent", "ClipboardWrite", "Payload", });
    internal_static_pbv1_IsReadyToPayRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pbv1_IsReadyToPayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_IsReadyToPayRequest_descriptor,
        new java.lang.String[] { "ApiVersion", "ApiVersionMinor", "AllowedPaymentMethods", "ExistingPaymentMethodRequired", });
    internal_static_pbv1_PaymentDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pbv1_PaymentDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_PaymentDataRequest_descriptor,
        new java.lang.String[] { "MerchantInfo", "ApiVersion", "ApiVersionMinor", "EmailRequired", "ShippingAddressRequired", "ShippingAddressParameters", "AllowedPaymentMethods", "TransactionInfo", "ShippingOptionRequired", "ShippingOptionParameters", });
    internal_static_pbv1_MerchantInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_pbv1_MerchantInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_MerchantInfo_descriptor,
        new java.lang.String[] { "MerchantId", "MerchantName", });
    internal_static_pbv1_ShippingAddressParameters_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_pbv1_ShippingAddressParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_ShippingAddressParameters_descriptor,
        new java.lang.String[] { "AllowedCountryCodes", "PhoneNumberRequired", });
    internal_static_pbv1_TransactionInfo_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_pbv1_TransactionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_TransactionInfo_descriptor,
        new java.lang.String[] { "TransactionId", "CurrencyCode", "CountryCode", "TotalPrice", "TotalPriceLabel", "TotalPriceStatus", "TransactionNote", "CheckoutOption", "DisplayItems", });
    internal_static_pbv1_DisplayItem_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_pbv1_DisplayItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_DisplayItem_descriptor,
        new java.lang.String[] { "Label", "Type", "Price", "Status", });
    internal_static_pbv1_ShippingOptionParameters_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_pbv1_ShippingOptionParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_ShippingOptionParameters_descriptor,
        new java.lang.String[] { "ShippingOptions", "DefaultSelectedOptionId", });
    internal_static_pbv1_ShippingOption_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_pbv1_ShippingOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_ShippingOption_descriptor,
        new java.lang.String[] { "Id", "Label", "Description", });
    internal_static_pbv1_PaymentData_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_pbv1_PaymentData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_PaymentData_descriptor,
        new java.lang.String[] { "ApiVersion", "ApiVersionMinor", "Email", "ShippingAddress", "PaymentMethodData", "ShippingOptionData", });
    internal_static_pbv1_SelectionOptionData_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_pbv1_SelectionOptionData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_SelectionOptionData_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_pbv1_PaymentMethodData_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_pbv1_PaymentMethodData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_PaymentMethodData_descriptor,
        new java.lang.String[] { "Type", "Info", "Description", "TokenizationData", });
    internal_static_pbv1_CardInfo_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_pbv1_CardInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_CardInfo_descriptor,
        new java.lang.String[] { "CardNetwork", "CardDetails", "BillingAddress", });
    internal_static_pbv1_Address_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_pbv1_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_Address_descriptor,
        new java.lang.String[] { "Name", "Address1", "Address2", "Address3", "Locality", "AdministrativeArea", "CountryCode", "PostalCode", "SortingCode", "PhoneNumber", });
    internal_static_pbv1_PaymentMethodTokenizationData_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_pbv1_PaymentMethodTokenizationData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_PaymentMethodTokenizationData_descriptor,
        new java.lang.String[] { "Type", "Token", });
    internal_static_pbv1_PaymentMethodSpecification_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_pbv1_PaymentMethodSpecification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_PaymentMethodSpecification_descriptor,
        new java.lang.String[] { "Type", "Parameters", "TokenizationSpecification", });
    internal_static_pbv1_CardParameters_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_pbv1_CardParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_CardParameters_descriptor,
        new java.lang.String[] { "AllowedAuthMethods", "AllowedCardNetworks", "AllowPrepaidCards", "AllowCreditCards", "BillingAddressRequired", "BillingAddressParameters", "CardNetworkParameters", });
    internal_static_pbv1_TokenizationSpecification_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_pbv1_TokenizationSpecification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_TokenizationSpecification_descriptor,
        new java.lang.String[] { "Type", "Parameters", });
    internal_static_pbv1_TokenizationSpecification_ParametersEntry_descriptor =
      internal_static_pbv1_TokenizationSpecification_descriptor.getNestedTypes().get(0);
    internal_static_pbv1_TokenizationSpecification_ParametersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_TokenizationSpecification_ParametersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_pbv1_BillingAddressParameters_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_pbv1_BillingAddressParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_BillingAddressParameters_descriptor,
        new java.lang.String[] { "Format", "PhoneNumberRequired", });
    internal_static_pbv1_CardNetworkParameters_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_pbv1_CardNetworkParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_CardNetworkParameters_descriptor,
        new java.lang.String[] { "CardNetwork", "AcquirerBin", "AcquirerMerchantId", });
    internal_static_pbv1_MobileError_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_pbv1_MobileError_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_MobileError_descriptor,
        new java.lang.String[] { "Code", "Message", "Description", });
    internal_static_pbv1_ApplePayPaymentDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_pbv1_ApplePayPaymentDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_ApplePayPaymentDataRequest_descriptor,
        new java.lang.String[] { "CountryCode", "CurrencyCode", "Total", });
    internal_static_pbv1_ApplePayTotal_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_pbv1_ApplePayTotal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_ApplePayTotal_descriptor,
        new java.lang.String[] { "Label", "Amount", });
    internal_static_pbv1_ApplePayPaymentData_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_pbv1_ApplePayPaymentData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_ApplePayPaymentData_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_pbv1_ApplePayPaymentToken_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_pbv1_ApplePayPaymentToken_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_ApplePayPaymentToken_descriptor,
        new java.lang.String[] { "PaymentData", "TransactionIdentifier", "PaymentMethod", });
    internal_static_pbv1_ApplePaymentMethod_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_pbv1_ApplePaymentMethod_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_ApplePaymentMethod_descriptor,
        new java.lang.String[] { "DisplayName", "Network", "Type", });
    internal_static_pbv1_MobileApplicationParams_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_pbv1_MobileApplicationParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_MobileApplicationParams_descriptor,
        new java.lang.String[] { "UserId", "DeviceId", "ConfirmationId", "PasswordEnabled", "BiometryEnabled", "BiometryAvailable", "FcmToken", "MyTrackerInstanceId", "AppmetricaDeviceId", });
    internal_static_pbv1_MobileApplicationParamsUpdate_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_pbv1_MobileApplicationParamsUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_MobileApplicationParamsUpdate_descriptor,
        new java.lang.String[] { "UserId", "ConfirmationId", "PasswordEnabled", "BiometryEnabled", });
    internal_static_pbv1_CreateKeysRequest_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_pbv1_CreateKeysRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_CreateKeysRequest_descriptor,
        new java.lang.String[] { "Password", });
    internal_static_pbv1_CreateKeysResponse_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_pbv1_CreateKeysResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_CreateKeysResponse_descriptor,
        new java.lang.String[] { "PublicKey", });
    internal_static_pbv1_MobileAnalyticsEvent_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_pbv1_MobileAnalyticsEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pbv1_MobileAnalyticsEvent_descriptor,
        new java.lang.String[] { "EventType", "Value", "UtmMedium", "UtmSource", "UtmCampaign", "UtmTerm", "UtmContent", "EmittedAt", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
