// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile.proto

package ru.gazprombonus.sdk.model;

public interface PaymentDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbv1.PaymentDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pbv1.MerchantInfo merchant_info = 1;</code>
   * @return Whether the merchantInfo field is set.
   */
  boolean hasMerchantInfo();
  /**
   * <code>.pbv1.MerchantInfo merchant_info = 1;</code>
   * @return The merchantInfo.
   */
  ru.gazprombonus.sdk.model.MerchantInfo getMerchantInfo();
  /**
   * <code>.pbv1.MerchantInfo merchant_info = 1;</code>
   */
  ru.gazprombonus.sdk.model.MerchantInfoOrBuilder getMerchantInfoOrBuilder();

  /**
   * <code>uint32 api_version = 2;</code>
   * @return The apiVersion.
   */
  int getApiVersion();

  /**
   * <code>uint32 api_version_minor = 3;</code>
   * @return The apiVersionMinor.
   */
  int getApiVersionMinor();

  /**
   * <code>bool email_required = 4;</code>
   * @return The emailRequired.
   */
  boolean getEmailRequired();

  /**
   * <code>bool shipping_address_required = 5;</code>
   * @return The shippingAddressRequired.
   */
  boolean getShippingAddressRequired();

  /**
   * <code>.pbv1.ShippingAddressParameters shipping_address_parameters = 6;</code>
   * @return Whether the shippingAddressParameters field is set.
   */
  boolean hasShippingAddressParameters();
  /**
   * <code>.pbv1.ShippingAddressParameters shipping_address_parameters = 6;</code>
   * @return The shippingAddressParameters.
   */
  ru.gazprombonus.sdk.model.ShippingAddressParameters getShippingAddressParameters();
  /**
   * <code>.pbv1.ShippingAddressParameters shipping_address_parameters = 6;</code>
   */
  ru.gazprombonus.sdk.model.ShippingAddressParametersOrBuilder getShippingAddressParametersOrBuilder();

  /**
   * <code>repeated .pbv1.PaymentMethodSpecification allowed_payment_methods = 7;</code>
   */
  java.util.List<ru.gazprombonus.sdk.model.PaymentMethodSpecification> 
      getAllowedPaymentMethodsList();
  /**
   * <code>repeated .pbv1.PaymentMethodSpecification allowed_payment_methods = 7;</code>
   */
  ru.gazprombonus.sdk.model.PaymentMethodSpecification getAllowedPaymentMethods(int index);
  /**
   * <code>repeated .pbv1.PaymentMethodSpecification allowed_payment_methods = 7;</code>
   */
  int getAllowedPaymentMethodsCount();
  /**
   * <code>repeated .pbv1.PaymentMethodSpecification allowed_payment_methods = 7;</code>
   */
  java.util.List<? extends ru.gazprombonus.sdk.model.PaymentMethodSpecificationOrBuilder> 
      getAllowedPaymentMethodsOrBuilderList();
  /**
   * <code>repeated .pbv1.PaymentMethodSpecification allowed_payment_methods = 7;</code>
   */
  ru.gazprombonus.sdk.model.PaymentMethodSpecificationOrBuilder getAllowedPaymentMethodsOrBuilder(
      int index);

  /**
   * <code>.pbv1.TransactionInfo transaction_info = 8;</code>
   * @return Whether the transactionInfo field is set.
   */
  boolean hasTransactionInfo();
  /**
   * <code>.pbv1.TransactionInfo transaction_info = 8;</code>
   * @return The transactionInfo.
   */
  ru.gazprombonus.sdk.model.TransactionInfo getTransactionInfo();
  /**
   * <code>.pbv1.TransactionInfo transaction_info = 8;</code>
   */
  ru.gazprombonus.sdk.model.TransactionInfoOrBuilder getTransactionInfoOrBuilder();

  /**
   * <code>bool shipping_option_required = 9;</code>
   * @return The shippingOptionRequired.
   */
  boolean getShippingOptionRequired();

  /**
   * <code>.pbv1.ShippingOptionParameters shipping_option_parameters = 10;</code>
   * @return Whether the shippingOptionParameters field is set.
   */
  boolean hasShippingOptionParameters();
  /**
   * <code>.pbv1.ShippingOptionParameters shipping_option_parameters = 10;</code>
   * @return The shippingOptionParameters.
   */
  ru.gazprombonus.sdk.model.ShippingOptionParameters getShippingOptionParameters();
  /**
   * <code>.pbv1.ShippingOptionParameters shipping_option_parameters = 10;</code>
   */
  ru.gazprombonus.sdk.model.ShippingOptionParametersOrBuilder getShippingOptionParametersOrBuilder();
}
