// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile.proto

package ru.gazprombonus.sdk.model;

public interface ShippingOptionParametersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbv1.ShippingOptionParameters)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .pbv1.ShippingOption shipping_options = 1;</code>
   */
  java.util.List<ru.gazprombonus.sdk.model.ShippingOption> 
      getShippingOptionsList();
  /**
   * <code>repeated .pbv1.ShippingOption shipping_options = 1;</code>
   */
  ru.gazprombonus.sdk.model.ShippingOption getShippingOptions(int index);
  /**
   * <code>repeated .pbv1.ShippingOption shipping_options = 1;</code>
   */
  int getShippingOptionsCount();
  /**
   * <code>repeated .pbv1.ShippingOption shipping_options = 1;</code>
   */
  java.util.List<? extends ru.gazprombonus.sdk.model.ShippingOptionOrBuilder> 
      getShippingOptionsOrBuilderList();
  /**
   * <code>repeated .pbv1.ShippingOption shipping_options = 1;</code>
   */
  ru.gazprombonus.sdk.model.ShippingOptionOrBuilder getShippingOptionsOrBuilder(
      int index);

  /**
   * <code>string default_selected_option_id = 2;</code>
   * @return The defaultSelectedOptionId.
   */
  java.lang.String getDefaultSelectedOptionId();
  /**
   * <code>string default_selected_option_id = 2;</code>
   * @return The bytes for defaultSelectedOptionId.
   */
  com.google.protobuf.ByteString
      getDefaultSelectedOptionIdBytes();
}
