// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile.proto

package ru.gazprombonus.sdk.model;

public interface TransactionInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbv1.TransactionInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string transaction_id = 1;</code>
   * @return The transactionId.
   */
  java.lang.String getTransactionId();
  /**
   * <code>string transaction_id = 1;</code>
   * @return The bytes for transactionId.
   */
  com.google.protobuf.ByteString
      getTransactionIdBytes();

  /**
   * <code>string currency_code = 2;</code>
   * @return The currencyCode.
   */
  java.lang.String getCurrencyCode();
  /**
   * <code>string currency_code = 2;</code>
   * @return The bytes for currencyCode.
   */
  com.google.protobuf.ByteString
      getCurrencyCodeBytes();

  /**
   * <code>string country_code = 3;</code>
   * @return The countryCode.
   */
  java.lang.String getCountryCode();
  /**
   * <code>string country_code = 3;</code>
   * @return The bytes for countryCode.
   */
  com.google.protobuf.ByteString
      getCountryCodeBytes();

  /**
   * <code>string total_price = 4;</code>
   * @return The totalPrice.
   */
  java.lang.String getTotalPrice();
  /**
   * <code>string total_price = 4;</code>
   * @return The bytes for totalPrice.
   */
  com.google.protobuf.ByteString
      getTotalPriceBytes();

  /**
   * <code>string total_price_label = 5;</code>
   * @return The totalPriceLabel.
   */
  java.lang.String getTotalPriceLabel();
  /**
   * <code>string total_price_label = 5;</code>
   * @return The bytes for totalPriceLabel.
   */
  com.google.protobuf.ByteString
      getTotalPriceLabelBytes();

  /**
   * <code>string total_price_status = 6;</code>
   * @return The totalPriceStatus.
   */
  java.lang.String getTotalPriceStatus();
  /**
   * <code>string total_price_status = 6;</code>
   * @return The bytes for totalPriceStatus.
   */
  com.google.protobuf.ByteString
      getTotalPriceStatusBytes();

  /**
   * <code>string transaction_note = 7;</code>
   * @return The transactionNote.
   */
  java.lang.String getTransactionNote();
  /**
   * <code>string transaction_note = 7;</code>
   * @return The bytes for transactionNote.
   */
  com.google.protobuf.ByteString
      getTransactionNoteBytes();

  /**
   * <code>string checkout_option = 8;</code>
   * @return The checkoutOption.
   */
  java.lang.String getCheckoutOption();
  /**
   * <code>string checkout_option = 8;</code>
   * @return The bytes for checkoutOption.
   */
  com.google.protobuf.ByteString
      getCheckoutOptionBytes();

  /**
   * <code>repeated .pbv1.DisplayItem display_items = 9;</code>
   */
  java.util.List<ru.gazprombonus.sdk.model.DisplayItem> 
      getDisplayItemsList();
  /**
   * <code>repeated .pbv1.DisplayItem display_items = 9;</code>
   */
  ru.gazprombonus.sdk.model.DisplayItem getDisplayItems(int index);
  /**
   * <code>repeated .pbv1.DisplayItem display_items = 9;</code>
   */
  int getDisplayItemsCount();
  /**
   * <code>repeated .pbv1.DisplayItem display_items = 9;</code>
   */
  java.util.List<? extends ru.gazprombonus.sdk.model.DisplayItemOrBuilder> 
      getDisplayItemsOrBuilderList();
  /**
   * <code>repeated .pbv1.DisplayItem display_items = 9;</code>
   */
  ru.gazprombonus.sdk.model.DisplayItemOrBuilder getDisplayItemsOrBuilder(
      int index);
}
